name: Tests

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    env:
      RACK_ENV: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Ruby and install gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: 3.4

      - name: Run tests
        run: |
          bundle exec rspec
